version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build and run unit tests
          command: dotnet test
workflows:
  test-workflow:
    jobs:
      - build
